name: newtoktech_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  excel: ^4.0.3
  file_picker: ^8.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  weather: ^3.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
