// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-FvnUzGL-K7bagAmnMeJFFbvykeIk7U',
    appId: '1:280636482486:web:399296ef2fefa815031717',
    messagingSenderId: '280636482486',
    projectId: 'newtoktech-task',
    authDomain: 'newtoktech-task.firebaseapp.com',
    storageBucket: 'newtoktech-task.appspot.com',
    measurementId: 'G-SXJ710N7QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNqQCEWkGpwGCnu1A3jUCX3aKXsfFSk8',
    appId: '1:280636482486:android:e33252687c2af2ef031717',
    messagingSenderId: '280636482486',
    projectId: 'newtoktech-task',
    storageBucket: 'newtoktech-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEsQnVY6aeuvQtNUwN8d8xLwW-VFI5C9E',
    appId: '1:280636482486:ios:2e66c788e08621df031717',
    messagingSenderId: '280636482486',
    projectId: 'newtoktech-task',
    storageBucket: 'newtoktech-task.appspot.com',
    iosBundleId: 'com.example.newtoktechTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEsQnVY6aeuvQtNUwN8d8xLwW-VFI5C9E',
    appId: '1:280636482486:ios:2e66c788e08621df031717',
    messagingSenderId: '280636482486',
    projectId: 'newtoktech-task',
    storageBucket: 'newtoktech-task.appspot.com',
    iosBundleId: 'com.example.newtoktechTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1-FvnUzGL-K7bagAmnMeJFFbvykeIk7U',
    appId: '1:280636482486:web:b0e1d80e5e77b691031717',
    messagingSenderId: '280636482486',
    projectId: 'newtoktech-task',
    authDomain: 'newtoktech-task.firebaseapp.com',
    storageBucket: 'newtoktech-task.appspot.com',
    measurementId: 'G-08GKWV36VQ',
  );
}
